### ISSUE TITLE
Clicking "Encode link" more than once doesn't work correctly

### ISSUE THREAD

**Issue by Gothdo** [Comandeer/fb-linker#2]
If after clicking the "Encode link" button I change the link and click the button again, the new encoded URL is appended to the field, without erasing the previous URL. For example, if I input `https://example.com/`, click the button, change the link to `https://example.com/42` and click the button again, the generated link is `https://comandeer.github.io/fb-linker/#aHR0cHM6Ly9leGFtcGxlLmNvbS8=aHR0cHM6Ly9leGFtcGxlLmNvbS80Mg==` instead of `https://comandeer.github.io/fb-linker/#aHR0cHM6Ly9leGFtcGxlLmNvbS80Mg==`.

**Comment by Comandeer** [comment]
Fixed with #3
